app/ContentSharing/page.js
app/Discussions/page.js
app/InquireAboutCrops/page.js
app/LearningAndResources/page.js
app/PersonalAiSupportBot/page.js
app/SeasonDashboard/page.js
app/UserProfiles/page.js
app/WeatherDashboard/page.js

- Implemented issue no. 11: Adding Folders and Files
- I have added all the folders and files with basic component for the features according to their names in `app` folder. eg. `app/UserProfiles/page.js`
- Please let me know if it is according to your requirements
Implements #11

adding files and folders

---

app/ContentSharing/page.js
app/Discussions/page.js
app/InquireAboutCrops/page.js
app/LearningAndResources/page.js
app/PersonalAiSupportBot/page.js
app/SeasonDashboard/page.js
app/UserProfiles/page.js
app/WeatherDashboard/page.js

Resolving Issue #15

---

app/components/Navbar.js

when the tab is small, changed the navbar to a side drawer.
added a few hover transitions to the existing navbar
implements #2

navbar ui component

---

app/components/LeftSideBar.js
app/dashboard/page.js
package-lock.json
package.json

added left side bar components

adding new code on dashboard,

---

app/contact/page.js

Key Changes:
- **Send Message** button color changed to theme green gradient and minimal hover effect.
- Implemented a side-by-side layout for the contact form and features section.
- Added a vertical line between the sections for visual clarity.
- Adjusted the background colors with the form color, maintaining the whole site theme.

ContactUS UI Improvement (Issue #7)

---

app/sign-in/page.js
app/sign-up/page.js

Fixes #9  Improve UI for sign-in page and make it better from previous one.
Now UI: 
@MOHAMMED-IQRAMUL  Please review my PR and see the above UI, If this works fine then please merge my PR with the labels:)

Design/signin UI

---

Contributing/README.md
app/sign-up/README.md
app/sign-up/page.js

issue #23 resolved 
This pull request includes several changes to enhance the Sign-Up page and update the contributing guidelines. The most important changes include adding a new contributor to the `README.md` file, adding an overview and usage instructions for the Sign-Up page, and improving the implementation of the Sign-Up page form.
* [`app/sign-up/README.md`](diffhunk://#diff-e7a66a446ea53f256af07bc52e1b9ff8f4c43fe131d2193dbbc2567bc87704aaR1-R28): Added an overview, features, usage instructions, and development guidelines for the Sign-Up page.
* [`app/sign-up/page.js`](diffhunk://#diff-a24f1222e34cbd93a73cc669d278c87cb633cbeddbac86aeb1fbea798c7703a8L1-R120): Improved the Sign-Up form by updating the input fields, removing redundant code, and ensuring better form validation and user …

Dedicated Signup Page for Website Users

---

app/terms/page.js

Fixes #14  Improve UI for Terms and services page and make it better from previous one and make interactive.
**Terms-And-Services-Page UI**
@MOHAMMED-IQRAMUL  Please review my PR and see the above UI, If this works fine then please merge my PR with the labels:)

Design: Terms and Services page

---

app/components/LogoutButton.js
app/components/Navbar.js

This pull request introduces a new `LogoutButton` component and integrates it into the existing `Navbar` component. 
* [`app/components/LogoutButton.js`](diffhunk://#diff-5ec7f85548bc96baafebc01e2beb01c121579919ffae458a8581fe993204fbeeR1-R21): Created a new `LogoutButton` component that handles user logout by removing the token from `localStorage` and redirecting to the home page.
* [`app/components/Navbar.js`](diffhunk://#diff-d23e7da04e4e60f058d0b7d1daff788462595c914b2f921a2cc063242f00c957R3): Imported the `LogoutButton` component and added it to the `Navbar` component.
https://github.com/user-attachments/assets/663d8c9f-89e0-475c-af1c-5461915d5079

Added Logout Button as a component and its functionality 

---

.gitignore
Backend/README.md
Backend/package.json
Backend/src/controllers/auth.controller.js
Backend/src/db/connection.js
Backend/src/index.js
Backend/src/models/user.model.js
Backend/src/routes/auth.routes.js
Backend/src/utils/generateToken.js
Contributing/README.md

This pull request includes the following updates to the backend:
- **Express Server Setup:** Configured the Express.js server to handle HTTP requests and manage routing for the application.
- **MongoDB Connection:** Established a connection to MongoDB using Mongoose, enabling schema-based data modeling.
- **Authentication System:** Implemented JWT (JSON Web Tokens) for user authentication, including routes for signup, login, and logout. Upon successful login, a JWT token is generated and sent back to the client.
- **User Model:** Created a Mongoose model to define the user schema, which includes fields for email, password (hashed), and methods for password validation and hashing.
- **Error Handling:** Added basic error handling for server issues, including managing port conflicts and …

Backend basic setup

---

app/contact/page.js

#7 
1. Added animation for Features section and also logos
2. Added animation on hover for input 
3. Added form validation checking for all boxes and error messages
4. Added shake animation on wrong input
5. Added loading bar on message submit
6. Updated form design
https://github.com/user-attachments/assets/c0089c64-af95-4348-bbb3-10e8c223576c

[FIX] #7 : Updated ContactUs Page

---

app/components/Navbar.js
app/components/ThemeToggle.js
app/globals.css
app/layout.js
app/page.js
package-lock.json
package.json

@MOHAMMED-IQRAMUL brother i have added dark and light mode feature , now please merge it brother

Added Dark and Light mode feature

---

app/about/page.js

Fixes #38
Bug Fixes
How to test - 
1) Go to about page
2) click on toggle button
3) Dark theme will be there

fixed the dark mode issue in about page

---

app/privacy/page.js

A complete redesign of the Privacy Policy page for the FarmRuler application. The goal was to enhance the user experience, improve readability, and ensure better visual appeal across different themes (light and dark mode).
The page now utilizes the full width of the screen for content, providing a more spacious and inviting layout.
Updated font styles for improved readability and aesthetic appeal.
Added consistent spacing and padding to various elements for a cleaner look.
Implemented a cohesive color scheme that adapts based on the selected theme (light/dark).
Included comprehensive sections on data collection, usage, security, and user rights.
Enhanced details on cookies policy and third-party services to ensure transparency.
Ensured that the page maintains usability and aesthetics on …

Redesign of Privacy Policy Page

---

app/faq/page.js
package-lock.json
package.json

added a filter option to it.
resolves #43

Add search functionality to FAQ page

---

app/page.js

closes #46 
On hovering sign-up button
On hovering sign-in button

fixing sign-up and sign-in button on hovering

---

app/page.js

improved homepage ui

---

Backend/README.md
Backend/package.json
Backend/src/controllers/auth.controller.js
Backend/src/middlewares/authenticateUser.middleware.js
Backend/src/utils/cleanedEnv.js
Backend/src/utils/dataValidator.js
Backend/src/utils/validationSchemas.js

- Readme file updated, proper data validation using joi library is done.
- Fixes #56

Refactor code to use data validation and cleaning functions

---

app/components/Navbar.js
app/page.js

#58 
Updated the "Sign-in" text into "Log-in" for better readability.

Update Sign-In to Log-In

---

Contributing/README.md
app/components/LeftSideBar.js
app/dashboard/page.js

Fix the Navbar so that it does not overlap with the content.

Fix the Navbar so that it does not overlap with the content.

---

app/components/Navbar.js

This update improves the Navbar by fixing its responsiveness and hover effects across both desktop and mobile views. It includes the addition of the "Dashboard" link to the mobile dropdown, ensures smoother dropdown transitions, and adjusts hover styles for the "About," "Contact," and "FAQ" links for a more consistent and visually appealing user experience. The background color and text styling in the dropdown have also been corrected to enhance clarity and overall UI design, making navigation seamless across all devices.

Fixed Navbar

---

app/about/page.js

Fixed Aboutus

---

app/sign-in/page.js

Improved login page responsiveness with CSS media queries and a flexible layout for seamless device adaptation. Enhanced UI aesthetics and accessibility for a polished and user-friendly experience.

Fixed Login Page Responsiveness and UI

---

app/sign-in/page.js
app/sign-up/page.js

Make Signup Page Responsive and Maintain Same design across both Login and SIgnup Form

Fixed Signup Page 

---

app/components/LeftSideBar.js
app/dashboard/page.js

Fix the UI, improve its appearance, and ensure responsiveness.

Fixed Dashboard

---

app/dashboard/page.js
app/page.js
tailwind.config.js

Resolved an issue where the dark/light theme toggle was not working as expected across the application.
- Properly integrated next-themes and wrapped the app with <ThemeProvider>.
- Added **_darkMode: "class"_** in tailwind.config.js to enable dark mode support.
This fix ensures a smooth theme-switching experience across all pages, improving the UI/UX consistency for users.
- Light and dark mode toggling across pages.
- Visual consistency in components.

Fix dark/light theme toggler issue

---

app/components/LogoutButton.js
app/components/Navbar.js
app/components/ThemeToggle.js
app/sign-up/page.js

- 🎨 Redesigned Navbar with solid green gradient background for better text visibility
- 🚀 Enhanced ThemeToggle with glassmorphism design and smooth animations
- 💫 Improved LogoutButton with gradient styling and icon integration
- 🔗 Added beautiful "Existing User? Sign In" section to signup page
- 🧹 Removed Log In button from header while keeping Sign Up button
- ✨ Added premium hover effects, transitions, and micro-interactions
- 📱 Enhanced mobile menu with better styling and organization
- 🎯 Maintained all existing functionality and authentication logic

✨ Enhanced header with beautiful UI improvements
